package citizenData;

public enum Region {
    BLAGOEVGRAD, BURGAS, VARNA, VELIKO_TARNOVO, VIDIN, VRATSA, GABROVO, KARDZHALI, KYUSTENSIL,
    LOVECH, MONTANA, PAZARZHIK, PERNIK, PLEVEN, PLOVDIV, RAZGRAD, RUSE, SILISTRA, SLIVEN, SMOLYAN,
    SOFIA_TOWN, SOFIA_REGION, STARA_ZAGORA, DOBRICH, TARGOVISHTE, HASKOVO, SHUMEN, YAMBOL, UNKNOWN
}
